Didi 729 ocultar boton mark as viewed
ong-bitcoin-argentina/DIDI-Ronda pull request #77
Opened 2020-11-20 16:53 UTC by jmartel-atixlabs

Si todas las notificaciones ya están leidas, oculta el botón de "Marcar como leídas".

También ajusta la redirección de las push notification

2020-11-24 12:45 UTC, MatiasOS requested changes

2020-11-24 12:45 UTC, MatiasOS commented on app/src/components/screens/Notifications/NotificationsList.js
> +              onPress={() => onMarkAsViewd()}>
Si hacemos `onPress={onMarkAsViewd}` debería hacer el trabajo y nos ahorramos el crear la función anónima. 

Puede ser que haya un typo? Le falta un **e** a `onMarkAsView **e** d`

2020-11-24 12:47 UTC, jmartel-atixlabs commented on app/src/components/screens/Notifications/NotificationsList.js
> +              onPress={() => onMarkAsViewd()}>
Si si, es verdad.. Lo ajusto (Y)

2020-11-24 16:05 UTC, nlaitanatix approved these changes

2020-11-24 16:05 UTC, nlaitanatix commented on app/src/components/screens/Notifications/NotificationsList.js
> +          {!isAllViewed ? (
Es mas claro asi me parece:
```suggestion
         {isAllViewed ? null : ...
```

2020-11-24 18:16 UTC, nlaitanatix approved these changes

2020-11-24 20:00 UTC, nlaitanatix approved these changes

2020-11-25 12:27 UTC, MatiasOS approved these changes
Esaa!!

2020-11-25 13:52 UTC, merged