Didi 769 fix push notification redirection
ong-bitcoin-argentina/DIDI-Ronda pull request #94
Opened 2020-12-15 17:47 UTC by jmartel-atixlabs

2020-12-15 20:25 UTC, nlaitanatix requested changes

2020-12-15 20:25 UTC, nlaitanatix commented on app/src/actions/rounds.js
> +    typeof data.action !== "object" ? JSON.parse(data.action) : data.action;
```suggestion
    typeof data.action.intent ? data.action : JSON.parse(data.action);
```

2020-12-15 20:25 UTC, nlaitanatix commented on app/src/components/screens/CreatedRound/ParticipantsList.js
> -      <FlatList
Aca porque sacaste la lista? Tengo entendido que estos componentes estan hechos porque performan mejor

2020-12-16 12:32 UTC, jmartel-atixlabs commented on app/src/components/screens/CreatedRound/ParticipantsList.js
> -      <FlatList
Estaba tirando un warning RN. Indicaba de que no deben ir FlatList dentro de ScrollViews que tengan el mismo sentido de orientación.

2020-12-16 13:21 UTC, nlaitanatix approved these changes

2020-12-16 15:00 UTC, merged